### ISSUE TITLE
Latest version 2.1.1 not available on Ansible Galaxy

### ISSUE THREAD

**Issue by Tybohurley** [geerlingguy/ansible-role-elasticsearch-curator#14]
The latest tagged release 2.1.1 is not available on Ansible Galaxy https://galaxy.ansible.com/ui/standalone/roles/?keywords=elasticsearch-curator
Would you be able to make it available there? Thanks

**Comment by geerlingguy** [comment]
Sure thing! Apparently I never updated the secret required for that update. Oops!

https://github.com/geerlingguy/ansible-role-elasticsearch-curator/actions/runs/8298501872
