### ISSUE TITLE
Update role for Curator 5.x

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-elasticsearch-curator#6]
Curator 4.x decided to change syntax/setup slightly... see https://github.com/geerlingguy/ansible-role-elasticsearch-curator/pull/5 and https://www.elastic.co/blog/curator_v4_release

We will need to start using the YML-based configuration instead of command line flags, and update everything to match.

**Comment by untergeek** [comment]
Curator 4.2 brought back the `curator_cli`, and Curator 5 is out now.

**Comment by geerlingguy** [comment]
Definitely need to do this; a few of my ES instances are not happy when I rebuild them because there isn't an `--older-than` option anymore.

**Comment by geerlingguy** [comment]
Had to do a bit of logstash/fluentd index maintenance on my main cluster to get all the changes here well-tested, but it looks like I have the settings all ready now. I am doing a final test and should then be able to push things up!
